In [ ]:
#importing the required libraries
from numpy import array
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Conv1D
from keras.layers import MaxPool1D
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Dense

In [ ]:
def split_sequence(sequence,steps):
  X,y=list(),list()
  for start in range(len(sequence)):
    end_index=start+steps
    if end_index > len(sequence)-1:
      break
    s_x,s_y=sequence[start:end_index],sequence[end_index]
    X.append(s_x)
    y.append(s_y)
  return array(X),array(y)


In [ ]:
raw_sequence=[100,110,120,130,140,150,160,170,180,190]
steps=3
X,y=split_sequence(raw_sequence,steps)
print("********")
print("The raw input is ")
print(raw_sequence)
print("********")
print("The features (X), lagged values of time series")
print(X)
print("The observed values (y), lagged values of time series")
print(y)


********
The raw input is 
[100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
********
The features (X), lagged values of time series
[[100 110 120]
 [110 120 130]
 [120 130 140]
 [130 140 150]
 [140 150 160]
 [150 160 170]
 [160 170 180]]
The observed values (y), lagged values of time series
[130 140 150 160 170 180 190]


In [ ]:
features=1
X=X.reshape((X.shape[0],X.shape[1],features))
print("********")

print(X.shape)
print("********")
print("Thefinal form of rese4arch matrix")
print(X)


********
(7, 3, 1)
********
Thefinal form of rese4arch matrix
[[[100]
  [110]
  [120]]

 [[110]
  [120]
  [130]]

 [[120]
  [130]
  [140]]

 [[130]
  [140]
  [150]]

 [[140]
  [150]
  [160]]

 [[150]
  [160]
  [170]]

 [[160]
  [170]
  [180]]]


In [ ]:
#defining model
model=Sequential()
#adding convolution layer
model.add(Conv1D(filters=64,kernel_size=2,activation='relu',input_shape=(steps,features)))
#adding pooling layer
model.add(MaxPool1D(pool_size=2))
#adding fully connected layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))

#adding output layer
model.add(Dense(1))
model.compile(loss='mse',optimizer='adam')
#fitting the model


In [ ]:
model.fit(X,y,epochs=10000,verbose=0)

In [ ]:
x_input=array([170,180,190])
x_input=x_input.reshape((1,steps,features))
y_pred=model.predict(x_input,verbose=0)
print("********")
print(f"The next predicted value {raw_sequence} is")
print(y_pred)
print("********")

********
The next predicted value [100, 110, 120, 130, 140, 150, 160, 170, 180, 190] is
[[200.0369]]
********


**Electric Production Dataset**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Electric_Production.csv',index_col=0, parse_dates=True)
Xt = df.values
print('Shape of data \t',df.shape)
print('Original Dataset: \n',df.head())
print('After Extracting only necessary values: \n',Xt)

Shape of data 	 (397, 1)
Original Dataset: 
             IPG2211A2N
DATE                  
1985-01-01     72.5052
1985-02-01     70.6720
1985-03-01     62.4502
1985-04-01     57.4714
1985-05-01     55.3151
After Extracting only necessary values: 
 [[ 72.5052]
 [ 70.672 ]
 [ 62.4502]
 [ 57.4714]
 [ 55.3151]
 [ 58.0904]
 [ 62.6202]
 [ 63.2485]
 [ 60.5846]
 [ 56.3154]
 [ 58.0005]
 [ 68.7145]
 [ 73.3057]
 [ 67.9869]
 [ 62.2221]
 [ 57.0329]
 [ 55.8137]
 [ 59.9005]
 [ 65.7655]
 [ 64.4816]
 [ 61.0005]
 [ 57.5322]
 [ 59.3417]
 [ 68.1354]
 [ 73.8152]
 [ 70.062 ]
 [ 65.61  ]
 [ 60.1586]
 [ 58.8734]
 [ 63.8918]
 [ 68.8694]
 [ 70.0669]
 [ 64.1151]
 [ 60.3789]
 [ 62.4643]
 [ 70.5777]
 [ 79.8703]
 [ 76.1622]
 [ 70.2928]
 [ 63.2384]
 [ 61.4065]
 [ 67.1097]
 [ 72.9816]
 [ 75.7655]
 [ 67.5152]
 [ 63.2832]
 [ 65.1078]
 [ 73.8631]
 [ 77.9188]
 [ 76.6822]
 [ 73.3523]
 [ 65.1081]
 [ 63.6892]
 [ 68.4722]
 [ 74.0301]
 [ 75.0448]
 [ 69.3053]
 [ 65.8735]
 [ 69.0706]
 [ 84.1949]
 [ 84.3598]
 [ 77.1726]
 [ 73.19

In [ ]:
X,y=split_sequence(Xt,steps)

In [ ]:
print("********")
print("The raw input is ")
print(Xt)
print("********")
print("The features (X), lagged values of time series")
print(X)
print("The observed values (y), lagged values of time series")
print(y)

********
The raw input is 
[[ 72.5052]
 [ 70.672 ]
 [ 62.4502]
 [ 57.4714]
 [ 55.3151]
 [ 58.0904]
 [ 62.6202]
 [ 63.2485]
 [ 60.5846]
 [ 56.3154]
 [ 58.0005]
 [ 68.7145]
 [ 73.3057]
 [ 67.9869]
 [ 62.2221]
 [ 57.0329]
 [ 55.8137]
 [ 59.9005]
 [ 65.7655]
 [ 64.4816]
 [ 61.0005]
 [ 57.5322]
 [ 59.3417]
 [ 68.1354]
 [ 73.8152]
 [ 70.062 ]
 [ 65.61  ]
 [ 60.1586]
 [ 58.8734]
 [ 63.8918]
 [ 68.8694]
 [ 70.0669]
 [ 64.1151]
 [ 60.3789]
 [ 62.4643]
 [ 70.5777]
 [ 79.8703]
 [ 76.1622]
 [ 70.2928]
 [ 63.2384]
 [ 61.4065]
 [ 67.1097]
 [ 72.9816]
 [ 75.7655]
 [ 67.5152]
 [ 63.2832]
 [ 65.1078]
 [ 73.8631]
 [ 77.9188]
 [ 76.6822]
 [ 73.3523]
 [ 65.1081]
 [ 63.6892]
 [ 68.4722]
 [ 74.0301]
 [ 75.0448]
 [ 69.3053]
 [ 65.8735]
 [ 69.0706]
 [ 84.1949]
 [ 84.3598]
 [ 77.1726]
 [ 73.1964]
 [ 67.2781]
 [ 65.8218]
 [ 71.4654]
 [ 76.614 ]
 [ 77.1052]
 [ 73.061 ]
 [ 67.4365]
 [ 68.5665]
 [ 77.6839]
 [ 86.0214]
 [ 77.5573]
 [ 73.365 ]
 [ 67.15  ]
 [ 68.8162]
 [ 74.8448]
 [ 80.0928]
 [ 79.1606]
 [ 73.5743]
 

In [ ]:
features=1
X=X.reshape((X.shape[0],X.shape[1],features))
print("********")

print(X.shape)
print("********")
print("Thefinal form of rese4arch matrix")
print(X)


********
(394, 3, 1)
********
Thefinal form of rese4arch matrix
[[[ 72.5052]
  [ 70.672 ]
  [ 62.4502]]

 [[ 70.672 ]
  [ 62.4502]
  [ 57.4714]]

 [[ 62.4502]
  [ 57.4714]
  [ 55.3151]]

 ...

 [[108.9312]
  [ 98.6154]
  [ 93.6137]]

 [[ 98.6154]
  [ 93.6137]
  [ 97.3359]]

 [[ 93.6137]
  [ 97.3359]
  [114.7212]]]


In [ ]:
#defining model
model=Sequential()
#adding convolution layer
model.add(Conv1D(filters=64,kernel_size=2,activation='relu',input_shape=(steps,features)))
#adding pooling layer
model.add(MaxPool1D(pool_size=2))
#adding fully connected layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))

#adding output layer
model.add(Dense(1))
model.compile(loss='mse',optimizer='adam')
#fitting the model


In [ ]:
model.fit(X,y,epochs=90,verbose=0)

In [ ]:
x_input=array([93.6137,97.3359,114.7212])
x_input=x_input.reshape((1,steps,features))
y_pred=model.predict(x_input,verbose=0)
print("********")
print(f"The next predicted value {Xt} is")
print(y_pred)
print("********")

********
The next predicted value [[ 72.5052]
 [ 70.672 ]
 [ 62.4502]
 [ 57.4714]
 [ 55.3151]
 [ 58.0904]
 [ 62.6202]
 [ 63.2485]
 [ 60.5846]
 [ 56.3154]
 [ 58.0005]
 [ 68.7145]
 [ 73.3057]
 [ 67.9869]
 [ 62.2221]
 [ 57.0329]
 [ 55.8137]
 [ 59.9005]
 [ 65.7655]
 [ 64.4816]
 [ 61.0005]
 [ 57.5322]
 [ 59.3417]
 [ 68.1354]
 [ 73.8152]
 [ 70.062 ]
 [ 65.61  ]
 [ 60.1586]
 [ 58.8734]
 [ 63.8918]
 [ 68.8694]
 [ 70.0669]
 [ 64.1151]
 [ 60.3789]
 [ 62.4643]
 [ 70.5777]
 [ 79.8703]
 [ 76.1622]
 [ 70.2928]
 [ 63.2384]
 [ 61.4065]
 [ 67.1097]
 [ 72.9816]
 [ 75.7655]
 [ 67.5152]
 [ 63.2832]
 [ 65.1078]
 [ 73.8631]
 [ 77.9188]
 [ 76.6822]
 [ 73.3523]
 [ 65.1081]
 [ 63.6892]
 [ 68.4722]
 [ 74.0301]
 [ 75.0448]
 [ 69.3053]
 [ 65.8735]
 [ 69.0706]
 [ 84.1949]
 [ 84.3598]
 [ 77.1726]
 [ 73.1964]
 [ 67.2781]
 [ 65.8218]
 [ 71.4654]
 [ 76.614 ]
 [ 77.1052]
 [ 73.061 ]
 [ 67.4365]
 [ 68.5665]
 [ 77.6839]
 [ 86.0214]
 [ 77.5573]
 [ 73.365 ]
 [ 67.15  ]
 [ 68.8162]
 [ 74.8448]
 [ 80.0928]
 [ 79.1606]
 [ 73.

In [ ]:
x_input=array([97.3359,114.7212,129.4048])
x_input=x_input.reshape((1,steps,features))
y_pred=model.predict(x_input,verbose=0)
print("********")
print(f"The next predicted value {Xt} is")
print(y_pred)
print("********")

********
The next predicted value [[ 72.5052]
 [ 70.672 ]
 [ 62.4502]
 [ 57.4714]
 [ 55.3151]
 [ 58.0904]
 [ 62.6202]
 [ 63.2485]
 [ 60.5846]
 [ 56.3154]
 [ 58.0005]
 [ 68.7145]
 [ 73.3057]
 [ 67.9869]
 [ 62.2221]
 [ 57.0329]
 [ 55.8137]
 [ 59.9005]
 [ 65.7655]
 [ 64.4816]
 [ 61.0005]
 [ 57.5322]
 [ 59.3417]
 [ 68.1354]
 [ 73.8152]
 [ 70.062 ]
 [ 65.61  ]
 [ 60.1586]
 [ 58.8734]
 [ 63.8918]
 [ 68.8694]
 [ 70.0669]
 [ 64.1151]
 [ 60.3789]
 [ 62.4643]
 [ 70.5777]
 [ 79.8703]
 [ 76.1622]
 [ 70.2928]
 [ 63.2384]
 [ 61.4065]
 [ 67.1097]
 [ 72.9816]
 [ 75.7655]
 [ 67.5152]
 [ 63.2832]
 [ 65.1078]
 [ 73.8631]
 [ 77.9188]
 [ 76.6822]
 [ 73.3523]
 [ 65.1081]
 [ 63.6892]
 [ 68.4722]
 [ 74.0301]
 [ 75.0448]
 [ 69.3053]
 [ 65.8735]
 [ 69.0706]
 [ 84.1949]
 [ 84.3598]
 [ 77.1726]
 [ 73.1964]
 [ 67.2781]
 [ 65.8218]
 [ 71.4654]
 [ 76.614 ]
 [ 77.1052]
 [ 73.061 ]
 [ 67.4365]
 [ 68.5665]
 [ 77.6839]
 [ 86.0214]
 [ 77.5573]
 [ 73.365 ]
 [ 67.15  ]
 [ 68.8162]
 [ 74.8448]
 [ 80.0928]
 [ 79.1606]
 [ 73.